services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wordlens
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine3.16
    ports:
      - "6379:6379"
